server:
  port: 8081
spring:
  datasource:
    username: "gelant_men"
    password: "test_123"
    url: "jdbc:mariadb://mysql-gelant.alwaysdata.net/gelant_menuiserie"

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
management:
  endpoints:
    web:
      base-path: 'api'
